version: '3.3'
services:
  cdktf-cli:
    # build: .
    image: cdktf-cli:latest
    command:
      - tail
      - -f
      - /dev/null
    volumes:
      - .:/src
      - ./data:/app
    working_dir: /app
